# Generated by Django 2.1.5 on 2019-05-05 17:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=45)),
                ('customer_phone', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('las_name', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=45)),
                ('direction', models.CharField(max_length=100, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('passwd', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Product_has_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('amount', models.SmallIntegerField()),
                ('description', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sale_date', models.DateField()),
                ('status', models.BooleanField()),
                ('id_customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Customers')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=450)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Provider'),
        ),
        migrations.AddField(
            model_name='product_has_sale',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Products'),
        ),
        migrations.AddField(
            model_name='product_has_sale',
            name='id_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Sales'),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsale.Users'),
        ),
    ]
