# Generated by Django 2.1.5 on 2019-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsale', '0002_auto_20190303_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='direction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
